### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by kiaralee** [hightechu/techccelerator-2022-template#5]
**Describe the solution you'd like**

- [ ] Update `Readme.md` with links to Docker and Handlebars (remove references to Heroku and EJS)
- [ ] Update `Getting_Started.md` with Docker deployment instructions (maybe @aabuelazm can do?)
- [ ] Update `Mentors_Info.md` with more complete instructions about deployment, workflow, etc.

**Comment by aabuelazm** [comment]
I'll add the docker documentation into the documentation branch and PR from there, but I'll add the new auth documentation into the auth branch and PR all of those at once.
